# Apply the Llama model 70B online

## Information

Inference API of Hugging Face exposes models that have large community interest and are in active use: https://huggingface.co/docs/api-inference/supported-models


**Precondition**: create an Access Token (https://huggingface.co/settings/tokens), set up a pro account to use the larger LLMs like Llama-3-70B (https://huggingface.co/pricing#pro) and accept the META LLAMA 3 COMMUNITY LICENSE AGREEMENT for the two different Llama models:

* for `meta-llama/Meta-Llama-3-70B-Instruct`: https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct

Remark: Llama models are published under the **META LLAMA 3 COMMUNITY LICENSE AGREEMENT**. The Meta Llama 3 Community License grants users a non-exclusive, royalty-free license (you not need to pay ongoing fees) to use, modify, and distribute Llama 3 materials, with requirements for attribution and naming conventions when creating derivative works. Users with over 700 million monthly active users need a separate license, and Meta disclaims all warranties and limits liability for any use of the materials.


***
**Coding sources**


* You can run the `meta-llama/Meta-Llama-3-70B-Instruct`, see model page: https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct
    + Hugging Face documentation: https://huggingface.co/docs/transformers/main/en/model_doc/llama3

## Load necessary libraries:

In [1]:
import os
import sys

# Assuming 'src' is two levels down (in the current directory or a subdirectory)
path_to_src = os.path.join('..')  # Moves one level down to 'src' folder

# Change the working directory
os.chdir(path_to_src)

# Verify the updated working directory
print("Updated working directory:", os.getcwd())

# load helper functions
import src.prompt_functions as pi
import src.prompt_text as pt
import src.get_data as get_data

Updated working directory: /home/fenn/Desktop/Publications/basal attributes/Analyses/part_III

load external data:

words of the single partitions and their respective mean_valence:

In [ ]:
import pandas as pd

df_partitions = pd.read_excel('./data/LeidenAlgorithm_solution.xlsx')
df_partitions.rename(columns={'parition': 'partition'}, inplace=True)

In [12]:
df_partitions

,partition,words,mean_valence,sd_valence
0,1,aktive Formänderung durch Umwelteinwirkung,0.18,1.140892
1,1,reaktionsfähig,0.67,1.111209
2,1,passive Formänderung durch Umwelteinwirkung,-0.02,1.131126
3,1,autonom,0.75,0.949819
4,1,passive Verhaltensänderung durch Umwelteinwirkung,0.06,1.056184
5,1,aktive Verhaltensänderung durch Umwelteinwirkung,0.27,1.148185
6,1,intelligent,1.35,1.103033
7,1,multifunktional,1.65,1.024702
8,1,technologisch,0.76,0.959081
9,2,zuverlässig,2.17,1.017770
10,2,wartungsfrei,1.75,1.158720
11,2,selbstheilend,1.65,1.124411
12,2,widerstandsfähig,1.74,1.053747
13,2,selbstreparierend,1.79,1.064389
14,2,haltbar,1.93,1.131655
15,2,robust,1.82,0.965705
16,2,langlebig,2.22,1.008592
17,3,wartungsintensiv,-2.04,1.008033
18,3,enthält Kunststoff,-1.04,1.125225
19,3,leicht zerstörbar,-1.80,1.403990
20,3,umweltschädlich,-2.60,0.927227
21,4,ökologisch,1.90,1.044515
22,4,elektronikfrei,0.46,1.074369
23,4,nachhaltig,2.38,0.981981
24,4,umweltfreundlich,2.49,0.932983
25,5,Energie speichernd,1.50,0.994774
26,5,energieeffizient,2.08,1.011835
27,5,energieautonom,1.43,1.067165
28,5,Energie generierend,1.72,1.181118
29,6,Insekten ähnlich,-0.12,1.143390
30,6,bioinspiriert,0.78,1.031929
31,6,lebensähnlich,0.33,0.922924

combination of partitions I want to generate a text from:

In [18]:
df_hypothesis= pd.read_excel('./data/LeidenAlgorithm_hypotheses.xlsx')
df_hypothesis.rename(columns={'partitionA': 'partitionA', 'partitionB': 'partitionB'}, inplace=True)

In [19]:
df_hypothesis = df_hypothesis[df_hypothesis['choose'] == 1][['partitionA', 'partitionB', 'mean']]
df_hypothesis

    partitionA  partitionB   mean
0            3           6 -0.545
2            3           5  0.130
5            1           6  0.480
9            1           5  1.155
11           1           2  1.255
14           2           4  1.845

In [6]:
pt=reload(pt)
prompt_text = pt.template_partitions
prompt_text

'\n\n\n\n<Aufgabe:\nEntwickle eine für Laien verständliche Beschreibung eines neuen Materialsystems für den Einsatz in einem realen Bau- oder Infrastrukturprojekt. Das Projekt sollte die Eigenschaften des Materials nutzen, um bestehende Probleme effektiv zu adressieren, während es auch auf mögliche Herausforderungen und Schwierigkeiten des Materialsystems eingeht. \n\n\nGenrell zeichnet sich das neue Materialsystem durch neuartige Eigenschaften aus, die es von herkömmlichen Materialien unterscheidet. Verwende hierzu alle Wörter aus der folgenden Liste, um die neuartigen Eigenschaften, aber auch die bestehenden Herausforderungen des Materialsystems zu beschreiben.>\n\n<Liste:\n({items_list})>\n\n<Aufgabenstellungen:\n1) Der Text muss weniger als 150 Wörter beinhalten.\n2) Schreibe neutral aus der Dritten Person und beziehe dich auf das konkrete Projekt.\n3) Achte bei der Verwendung der Wörter darauf, nicht Wörter mit unterschiedlichen emotionalen Konnotationen zu vermischen.\n4) Das Projekt muss konkret und plausibel sein.\n5) Beginne mit einem einleitenden kurzen Satz, der das Projekt beschreibt.\n6) Gehe Schritt für Schritt vor. \n7) Verwende alle Wörter, die in der Liste angegeben sind.>\n\n    Answer: '

In [7]:
pi=reload(pi)
chosen_partitions = [1, 2] 
examplary_template = pi.prompt_template(df_partitions, chosen_partitions, prompt_text)
print(examplary_template)

<Aufgabe:
Entwickle eine für Laien verständliche Beschreibung eines neuen Materialsystems für den Einsatz in einem realen Bau- oder Infrastrukturprojekt. Das Projekt sollte die Eigenschaften des Materials nutzen, um bestehende Probleme effektiv zu adressieren, während es auch auf mögliche Herausforderungen und Schwierigkeiten des Materialsystems eingeht.


Genrell zeichnet sich das neue Materialsystem durch neuartige Eigenschaften aus, die es von herkömmlichen Materialien unterscheidet. Verwende hierzu alle Wörter aus der folgenden Liste, um die neuartigen Eigenschaften, aber auch die bestehenden Herausforderungen des Materialsystems zu beschreiben.>

<Liste:
(aktive Formänderung durch Umwelteinwirkung, reaktionsfähig, passive Formänderung durch Umwelteinwirkung, autonom, passive Verhaltensänderung durch Umwelteinwirkung, aktive Verhaltensänderung durch Umwelteinwirkung, intelligent, multifunktional, technologisch, zuverlässig, wartungsfrei, selbstheilend, widerstandsfähig, selbstreparierend, haltbar, robust, langlebig)>

<Aufgabenstellungen:
1) Der Text muss weniger als 150 Wörter beinhalten.
2) Schreibe neutral aus der Dritten Person und beziehe dich auf das konkrete Projekt.
3) Achte bei der Verwendung der Wörter darauf, nicht Wörter mit unterschiedlichen emotionalen Konnotationen zu vermischen.
4) Das Projekt muss konkret und plausibel sein.
5) Beginne mit einem einleitenden kurzen Satz, der das Projekt beschreibt.
6) Gehe Schritt für Schritt vor.
7) Verwende alle Wörter, die in der Liste angegeben sind.>

    Answer:

In [8]:
key=reload(key)
api_key = key.openai_api_key

NameError: name 'key' is not defined

In [9]:
## remove tuples
import itertools
unique_partitions = df_partitions["partition"].unique()
all_combinations = list(itertools.combinations(unique_partitions, 2))
print(all_combinations)
# Tuples to remove
to_remove = {(3, 5), (2, 3)}
# Filter out the tuples that are to be removed
filtered_combinations = [t for t in all_combinations if t not in to_remove]
print(filtered_combinations)

[(1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 3), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6), (4, 5), (4, 6), (5, 6)]
[(1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 6), (4, 5), (4, 6), (5, 6)]

In [10]:
result, full_response = pi.process_partitions(df_partitions, prompt_text, api_key, model="gpt-4", chosen_partitions=[(3,6)], max_tokens=500, max_API_calls=1)

NameError: name 'api_key' is not defined

In [ ]:
full_response

In [ ]:
result

In [ ]:
get_data.save_results_to_csv('result.csv', result)

In [ ]:
result_df = pd.read_csv('./output/result.csv')

In [ ]:
get_data=reload(get_data)
text_check = get_data.check_for_missing_matching_words(result_df['text'], df_partitions, [3,6], 0.5)
print(text_check)